### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by dftossem** [aws-robotics/aws-iot-bridge-example#10]
Hi,

I am trying to connect a ROS device to AWS IoT Core, I have followed the docs:

- [Create a Thing](https://docs.aws.amazon.com/iot/latest/developerguide/create-aws-thing.html)
- [Register a Device](https://docs.aws.amazon.com/iot/latest/developerguide/register-device.html)
- [Configure Your Device](https://docs.aws.amazon.com/iot/latest/developerguide/configure-iot.html)

I [created and downloaded](https://docs.aws.amazon.com/iot/latest/developerguide/create-device-certificate.html) the certificates, the [mqtt_bridge package](https://github.com/groove-x/mqtt_bridge.git) is working well, and finally I have made the changes in:

aws_iot_params.yaml
```python
tls:
  ca_certs: certs/amazonRootCA1.pem
  certfile: certs/certificate.pem
  keyfile: certs/private.pem
connection:
  host: ENDPOINT.iot.us-east-1.amazonaws.com
```
And aws_iot_bridge.launch
```xml
<rosparam param="mqtt/tls/ca_certs" subst_value="true">$(find aws_iot_mqtt_bridge)/config/certs/amazonRootCA1.pem</rosparam>
<rosparam param="mqtt/tls/certfile" subst_value="true">$(find aws_iot_mqtt_bridge)/config/certs/certificate.pem</rosparam>
<rosparam param="mqtt/tls/keyfile" subst_value="true">$(find aws_iot_mqtt_bridge)/config/certs/private.pem</rosparam>
```
The amazonRootCA1.pem file has [this data](https://www.amazontrust.com/repository/AmazonRootCA1.pem) and the ENDPOINT information comes from the output of _aws iot describe endpoint_ (AWS CLI)

Finally, here is my file tree

```
aws-iot-bridge-example
├── aws_iot_mqtt_bridge
│   ├── CMakeLists.txt
│   ├── config
│   │   ├── aws_iot_params.yaml
│   │   └── certs
│   │       ├── certificate.pem
│   │       ├── private.pem
│   │       └── amazonRootCA1.pem
│   ├── launch
│   │   └── aws_iot_bridge.launch
│   ├── LICENSE.txt
│   ├── NOTICE.txt
│   ├── package.xml
│   ├── README.md
│   └── rosdep
│       └── mqtt-bridge.yaml
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
├── LICENSE
└── README.md
```

Unfortunately I have this error:

```bash
SUMMARY
========

PARAMETERS
 * /mqtt_bridge/client/protocol: 4
 * /mqtt_bridge/connection/host: ENDPOINT.io...
 * /mqtt_bridge/connection/keepalive: 60
 * /mqtt_bridge/connection/port: 8883
 * /mqtt_bridge/mqtt/client/protocol: 4
 * /mqtt_bridge/mqtt/connection/host: ENDPOINT.io...
 * /mqtt_bridge/mqtt/connection/keepalive: 60
 * /mqtt_bridge/mqtt/connection/port: 8883
 * /mqtt_bridge/mqtt/tls/ca_certs: /home/dftossem/ca...
 * /mqtt_bridge/mqtt/tls/certfile: /home/dftossem/ca...
 * /mqtt_bridge/mqtt/tls/keyfile: /home/dftossem/ca...
 * /mqtt_bridge/mqtt/tls/tls_insecure: False
 * /mqtt_bridge/mqtt/tls/tls_version: 5
 * /mqtt_bridge/tls/ca_certs: certs/amazonRootC...
 * /mqtt_bridge/tls/certfile: certs/XXXXXXXX-...
 * /mqtt_bridge/tls/keyfile: certs/XXXXXXXX-...
 * /mqtt_bridge/tls/tls_insecure: False
 * /mqtt_bridge/tls/tls_version: 5
 * /rosdistro: melodic
 * /rosversion: 1.14.5

NODES
  /
    mqtt_bridge (mqtt_bridge/mqtt_bridge_node.py)

auto-starting new master
process[master]: started with pid [13538]
ROS_MASTER_URI=http://192.168.1.63:11311

setting /run_id to 6f899a16-8927-11ea-8a33-3c9509c5da29
process[rosout-1]: started with pid [13549]
started core service [/rosout]
process[mqtt_bridge-2]: started with pid [13556]
Traceback (most recent call last):
  File "/home/dftossem/catkin_ws/src/mqtt_bridge/scripts/mqtt_bridge_node.py", line 9, in <module>
    mqtt_bridge_node()
  File "/home/dftossem/catkin_ws/src/mqtt_bridge/src/mqtt_bridge/app.py", line 56, in mqtt_bridge_node
    mqtt_client.connect(**conn_params)
  File "/home/dftossem/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/home/dftossem/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1100, in reconnect
    sock.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
```

Thanks in advance

**Comment by capeie-dev** [comment]
Do you also get this error when you run the following command?:
`rosrun mqtt_bridge mqtt_bridge_node.py`

Error:
`Traceback (most recent call last):
  File "/home/capeie/catkin_ws/src/mqtt_bridge/scripts/mqtt_bridge_node.py", line 9, in <module>
    mqtt_bridge_node()
  File "/home/capeie/catkin_ws/src/mqtt_bridge/src/mqtt_bridge/app.py", line 36, in mqtt_bridge_node
    conn_params = mqtt_params.pop('connection')
KeyError: 'connection'`

**Comment by dftossem** [comment]
Yes, but the reason is that the roslaunch file is passing the right arguments (*.yaml files) to the mqtt_bridge node at this lines:
```
<rosparam command="load" file="$(find mqtt_bridge)/config/demo_params.yaml" />
<rosparam if="$(arg use_tls)" command="load" ns="mqtt" file="$(find mqtt_bridge)/config/tls_params.yaml" />
```
So, they are missing in this command `rosrun mqtt_bridge mqtt_bridge_node.py`. I recommend edit the configuration files (*.yaml) and the use of the launch file as well.

**Comment by capeieboi** [comment]
I am also facing the same issue and had some progress by changing setting `cert_reqs=ssl.CERT_NONE`
I edited the `mqtt_bridge` package to test, following file: (catkin_ws)/src/mqtt_bridge/src/mqtt_bridge/mqtt_client.py

The following lines under #configure tls:
`tls_insecure = True`
`client.tls_set(**tls_params) to client.tls_set("(path to amazonca1.pem)",certfile="(path to certfile)",keyfile="(path to private keyfile)",tls_version=5, cert_reqs=ssl.CERT_NONE)`

It shows it is connected at the iot core console, however I am getting the following error when I run `roslaunch aws_iot_mqtt_bridge ... `:
`[INFO] [1588176802.247191]: MQTT disconnected
[INFO] [1588176803.473111]: MQTT disconnected
[INFO] [1588176804.707820]: MQTT disconnected
[INFO] [1588176806.024323]: MQTT disconnected
[INFO] [1588176807.250039]: MQTT disconnected
[INFO] [1588176808.481376]: MQTT disconnected
`
Kindly help

**Comment by dftossem** [comment]
- Update: Error continues :(

- Alternative: Use AWSIoTPythonSDK

1. Go to AWS IoT Core
2. Click 'Onboard'
3. Click 'Get started' in Onboard a device 
3.1. Register a device
3.2. Download a connection kit
4. Go to Downloads and Unzip the folder
5. Open a terminal and go to the downloaded folder path

```
cd connect_device_package/
chmod +x start.sh
./start.sh
```

The final step of the ./start.sh command shows a successful connection with AWS IoT using MQTT and publishing _sdk/test/Python_ topic:

```
Received a new message: 
{"message": "Hello World!", "sequence": 0}
from topic: 
sdk/test/Python
```
What now? Create a ROS node or adapt ROS mqtt node

**Comment by dftossem** [comment]
Good news, I did it (publish the topic on AWS IoT Core). I made a new [repository](https://github.com/dftossem/mqtt_ros_aws_iot) for this.

INFO: There still are work to do such as receive messages from AWS IoT Core page (subscribe)

**Comment by ericson-cepeda** [comment]
In my case, the rootCA.pem was invalid: https://stackoverflow.com/a/69291772/1705127
