### ISSUE TITLE
Running `rosdep install` gives a 404 error on mqtt-bridge.yaml

### ISSUE THREAD

**Issue by jbnunn** [aws-robotics/aws-iot-bridge-example#3]
When running `rosdep install --from-paths src --ignore-src -r -y` per the README, an error of 

    HTTP Error 404: Not Found (https://raw.githubusercontent.com/aws-robotics/aws-iot-bridge-example/aws_iot_mqtt_bridge/rosdep/gh-pages/mqtt-bridge.yaml)

is thrown.

**Comment by ryanewel** [comment]
Could you give some more information on what environment you're running `rosdep install` in?
When I try this in the ros:kinetic docker container it builds fine

For reference my steps to build are:
```
docker pull ros:kinetic
docker run -it <image_id> /bin/bash
apt-get update
apt-get install python-pip
apt-get install python3-colcon-common-extensions
source /opt/ros/kinetic/local_setup.bash
rosdep update
mkdir -p /iot_ws/src && cd /iot_ws/src
git clone -b release-v1 https://github.com/aws-robotics/aws-iot-bridge-example.git
cd /iot_ws
rosdep install --from-paths src --ignore-src -r -y
colcon build
```

**Comment by jbnunn** [comment]
Thanks @ryanewel. I'm running in a Melodic RoboMaker environment. In [https://github.com/aws-robotics/aws-iot-bridge-example/blob/release-v1/aws_iot_mqtt_bridge/README.md#setting-up-mqtt_bridge](https://github.com/aws-robotics/aws-iot-bridge-example/blob/release-v1/aws_iot_mqtt_bridge/README.md#setting-up-mqtt_bridge), we're writing an invalid link to /etc/ros/rosdep/sources.list.d/30-mqtt-bridge.list

If you curl the link given, you get a 404: 

    curl https://raw.githubusercontent.com/aws-robotics/aws-iot-bridge-example/aws_iot_mqtt_bridge/rosdep/gh-pages/mqtt-bridge.yaml

**Comment by ryanewel** [comment]
Sorry about the delay.
That looks like a mistake in the documentation. I think the command should be 
```
sudo bash -c "echo \"yaml https://raw.githubusercontent.com/aws-robotics/aws-iot-bridge-example/release-v1/aws_iot_mqtt_bridge/rosdep/mqtt-bridge.yaml\" > /etc/ros/rosdep/sources.list.d/30-mqtt-bridge.list"
```
`rosdep update` runs with this command.

However it looks like a dependency of this package `mqtt_bridge` hasn't been released for melodic. So you may have to build that from source if you want to continue using melodic

**Comment by AAlon** [comment]
Closing, @jbnunn please feel free to reopen if you're still having issues.
