### ISSUE TITLE
binary install via `apt` installs wrong package?

### ISSUE THREAD

**Issue by yuta-imai** [aws-robotics/aws-iot-bridge-example#6]
Hi, when I run binary installation procedure as described in README like

```
sudo apt-get update
sudo apt-get install -y ros-kinetic-iot-bridge
```

I get the package below installed. I don't think this is the right package.
http://wiki.ros.org/iot_bridge

My env:
- ROS Kinetic
- Ubuntu 16.04 on Raspberry Pi 3B+
- The OS image I am using the below. This is the robot vendor based image but `/etc/apt/sources.list.d` includes `ros-latest.list` which points `http://packages.ros.org/ros/ubuntu`
  - https://downloads.ubiquityrobotics.com/pi.html

**Comment by mm318** [comment]
Hi @yuta-imai, thank you for bringing this to our attention. It looks like `apt install ros-kinetic-iot-bridge` actually installs https://github.com/corb555/iot_bridge. Sorry for the confusion.

**Comment by mm318** [comment]
The README has been corrected.
